#!/bin/bash

ODOO_VERSION=master
ODOO_TIMESTAMP=20140517-231234
ODOO_URL=https://github.com/odoo/odoo/archive/$ODOO_VERSION.zip

cp ${OPENSHIFT_REPO_DIR}/wkhtmltopdf/wkhtmltopdf ${OPENSHIFT_PYTHON_DIR}/virtenv/bin
cp ${OPENSHIFT_REPO_DIR}/wkhtmltopdf/lib/* ${OPENSHIFT_PYTHON_DIR}/virtenv/bin
cd $OPENSHIFT_REPO_DIR

echo "Odoo will be compiled now."
  source $OPENSHIFT_PYTHON_DIR/virtenv/bin/activate
  #pip install -r $OPENSHIFT_REPO_DIR/requirements.txt
  
  cd $OPENSHIFT_REPO_DIR/odoo
  sed -i '/python-ldap/d' setup.py
  python setup.py develop

