#!/bin/bash

ODOO_VERSION=8.0
ODOO_TIMESTAMP=20140517-231234
ODOO_URL=https://github.com/odoo/odoo/archive/$ODOO_VERSION.zip

cd $OPENSHIFT_DATA_DIR/

if [ -d "odoo-${ODOO_VERSION}" ]; then
	echo "Odoo already downloaded."
	exit 0
fi

echo "Odoo will be downloaded now."
wget $ODOO_URL

unzip odoo-${ODOO_VERSION}.zip

ln -s $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION}/requirements.txt $OPENSHIFT_DATA_DIR/requirements.txt

