#!/bin/bash

ODOO_VERSION=8.0
ODOO_TIMESTAMP=20140517-231234
ODOO_URL=https://github.com/odoo/odoo/archive/$ODOO_VERSION.zip

cp ${OPENSHIFT_REPO_DIR}/wkhtmltopdf/wkhtmltopdf ${OPENSHIFT_PYTHON_DIR}/virtenv/bin
cp ${OPENSHIFT_REPO_DIR}/wkhtmltopdf/lib/* ${OPENSHIFT_PYTHON_DIR}/virtenv/bin
cd $OPENSHIFT_DATA_DIR

#if [ -d "odoo-${ODOO_VERSION}" ]; then
#	echo "Odoo already downloaded."
#	exit 0
#fi

if [ ! -f "$OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION}-${ODOO_TIMESTAMP}.zip" ]; then
  echo "Odoo will be downloaded now."
  #rm -f $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION}-${ODOO_TIMESTAMP}.zip
  wget $ODOO_URL -O $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION}-${ODOO_TIMESTAMP}.zip

  unzip -o $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION}-${ODOO_TIMESTAMP}.zip

  rm -f $OPENSHIFT_DATA_DIR/odoo
  ln -s $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION} $OPENSHIFT_DATA_DIR/odoo

  #rm -f $OPENSHIFT_REPO_DIR/requirements.txt
  #ln -s $OPENSHIFT_DATA_DIR/odoo/requirements.txt $OPENSHIFT_REPO_DIR/requirements.txt

  source $OPENSHIFT_PYTHON_DIR/virtenv/bin/activate
  #pip install -r $OPENSHIFT_REPO_DIR/requirements.txt
  
  cd $OPENSHIFT_DATA_DIR/odoo
  sed -i '/python-ldap/d' setup.py
  python setup.py develop
fi
#export XDG_DATA_HOME = $OPENSHIFT_DATA_DIR/.local/share
#export XDG_CACHE_HOME = $OPENSHIFT_DATA_DIR/.cache
#export XDG_CONFIG_HOME = $OPENSHIFT_DATA_DIR/.config

#cd $OPENSHIFT_DATA_DIR/odoo
#XDG_DATA_HOME="$OPENSHIFT_DATA_DIR/.local/share" ./openerp-server --update=all --stop-after-init -d $OPENSHIFT_APP_NAME -r $OPENSHIFT_POSTGRESQL_DB_USERNAME -w $OPENSHIFT_POSTGRESQL_DB_PASSWORD --db_host=$OPENSHIFT_POSTGRESQL_DB_HOST --db_port=$OPENSHIFT_POSTGRESQL_DB_PORT --addons-path="$OPENSHIFT_REPO_DIR/addons,$OPENSHIFT_DATA_DIR/odoo/addons,$OPENSHIFT_DATA_DIR/odoo/openerp/addons"

#rm $OPENSHIFT_DATA_DIR/odoo-${ODOO_VERSION}.zip
