#!/bin/bash

source ${OPENSHIFT_PYTHON_DIR}/virtenv/bin/activate

cd $OPENSHIFT_REPO_DIR/odoo
XDG_DATA_HOME="$OPENSHIFT_DATA_DIR/.local/share" ./openerp-server --update=all --stop-after-init -d $OPENSHIFT_APP_NAME -r $OPENSHIFT_POSTGRESQL_DB_USERNAME -w $OPENSHIFT_POSTGRESQL_DB_PASSWORD --db_host=$OPENSHIFT_POSTGRESQL_DB_HOST --db_port=$OPENSHIFT_POSTGRESQL_DB_PORT --addons-path="$OPENSHIFT_REPO_DIR/addons,$OPENSHIFT_REPO_DIR/odoo/addons,$OPENSHIFT_REPO_DIR/odoo/openerp/addons"


