#!/usr/bin/env python
# WSGI Handler sample configuration file.
#
# Change the appropriate settings below, in order to provide the parameters
# that would normally be passed in the command-line.
# (at least conf['addons_path'])
#
# For generic wsgi handlers a global application is defined.
# For uwsgi this should work:
#   $ uwsgi_python --http :9090 --pythonpath . --wsgi-file ODOO-wsgi.py
#
# For gunicorn additional globals need to be defined in the Gunicorn section.
# Then the following command should run:
#   $ gunicorn ODOO:service.wsgi_server.application -c ODOO-wsgi.py

import os
import sys

ODOO_ROOT_DIR = os.path.join(os.environ.get('OPENSHIFT_REPO_DIR', '.'), 'wsgi/ODOO')
if ODOO_ROOT_DIR not in sys.path:
    sys.path.append(ODOO_ROOT_DIR)

import ODOO

#----------------------------------------------------------
# Common
#----------------------------------------------------------
ODOO.multi_process = True # Nah!

# Equivalent of --load command-line option
ODOO.conf.server_wide_modules = ['web']
conf = ODOO.tools.config

# Path to the ODOO Addons repository (comma-separated for
# multiple locations)

conf['addons_path'] = os.path.join(ODOO_ROOT_DIR, 'ODOO/addons')

# Optional database config if not using local socket
conf['db_host']     = os.environ['OPENSHIFT_POSTGRESQL_DB_HOST']
conf['db_port']     = int(os.environ['OPENSHIFT_POSTGRESQL_DB_PORT'])
conf['db_user']     = os.environ['OPENSHIFT_POSTGRESQL_DB_USERNAME']
conf['db_name']     = os.environ['OPENSHIFT_APP_NAME']
conf['db_password'] = os.environ['OPENSHIFT_POSTGRESQL_DB_PASSWORD']

#----------------------------------------------------------
# Generic WSGI handlers application
#----------------------------------------------------------
application = ODOO.service.wsgi_server.application

#----------------------------------------------------------
# Gunicorn
#----------------------------------------------------------
# Standard ODOO XML-RPC port is 8069
#bind = '127.0.0.1:8069'
#pidfile = '.gunicorn.pid'
#workers = 4
#timeout = 240
#max_requests = 2000

#
# Below for testing only
#
if __name__ == '__main__':
    from wsgiref.simple_server import make_server
    httpd = make_server('localhost', 8051, application)
    # Wait for a single request, serve it and quit.
    httpd.handle_request()

# vim:expandtab:smartindent:tabstop=4:softtabstop=4:shiftwidth=4:
